### ISSUE TITLE
Change `tqec.templates.constructions` classes constructors to remove the scalable dimension

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#101]
> > I think we should replace width and height by k_width and k_height, for the same reasons explained above.
> 
> The problem with that is a `ScalableQubitRectangle` can have an odd-size width/height.
> 
> > Also, this raises a more fundamental question: the dimension/scale provided at construction is kind of redundant if we impose a to_scale call. 
> 
> I agree with your opnion and prefer the first way. For the `ScalableQubitRectangle`, we can specify only the fixed dimension during construction while leaving the scalable dimension to be determined by the later call of `scale_to`.

_Originally posted by @inmzhang in https://github.com/QCHackers/tqec/issues/97#issuecomment-1921364943_

Only the fixed dimensions should appear in the constructors, and the user is expected to call the `scale_to` method to actually scale the template to the desired size.

**Comment by nelimee** [comment]
Requiring the user to use the `scale_to` method after creating the template seems odd to me. This implies that the instance is not fully constructed after the `__init__` method. Thinking about it, I would prefer option 2

> keep the `dim`/`scale`/`k` parameter in the construction API, do the same as point 1. and finish by calling `to_scale(k)` in the constructor.

as it would be less error-prone for the user.

**Comment by inmzhang** [comment]
I used to prefer the 1st option because I thought the dimension of a rectangle can be odd. Then it's hard to use scale `k` to specify all the dimension of a rectangle. With the [comment](https://github.com/QCHackers/tqec/pull/97#issuecomment-1921448758), `k` seems can be used throughout the basic constructions, now I prefer the 2nd option.

**Comment by afowler** [comment]
My vote goes for 2k controlling width and height, no rectangular templates.
Too much complexity for too little benefit.
