### ISSUE TITLE
Add option to scale a `ScalableQubitRectangle` with the fixed aspect ratio

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#102]
> For another consideration, there are circumstances where we want to scale both of the dimension of a rectangle but with a fixed aspect ratio(for example, when study the surface code for the biased-noise). we can make it more general with an option to scale both of the dimension with a fixed aspect ratio, but this needs a change to the underlying shape implementation.

Originally posted in [#97 comment](https://github.com/QCHackers/tqec/pull/97#issuecomment-1921448758).

**Comment by inmzhang** [comment]
With [the comments](https://github.com/QCHackers/tqec/pull/97#issuecomment-1922164908) from @afowler, we should avoid to introduce this complexity into the project. I agree with this and intend to close this issue. What's your thoughts on this, @nelimee?

**Comment by nelimee** [comment]
If it is not needed for expressiveness, we do not want additional complexity. Let's close that.
