### ISSUE TITLE
Create TQEC readthedocs site

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#109]
- [ ] Basic description of the library (focused on the backend)
- [ ] Tutorials
- [ ] Code examples
- [ ] Contribution guidelines

**Comment by smburdick** [comment]
Thanks @nelimee

**Comment by nelimee** [comment]
I thought that ReadTheDocs was a simple Sphinx theme, but it turns out it is not. I am unassigning myself for the moment, I may reassign if I have more time to dig into that, but anyone feel free to take that issue.

**Comment by nelimee** [comment]
Also, as soon as we do have a RdT documentation, the outputs of the Jupyter notebooks should go away and be replaced by that online documentation.

**Comment by Gistbatch** [comment]
Can we add a "How to contribute" section? This would help #113, #118, #94, and potentially more.

**Comment by nelimee** [comment]
I think this issue is solved by the GitHub Pages website: [qchackers.github.io/tqec/](https://qchackers.github.io/tqec/). If someone thinks this is not the case, please re-open.
