### ISSUE TITLE
 Compatibility issue of new python features

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#110]
There are some python features only available for newer python version in the current codebase. For example:
- Use `dict`/`tuple` instead of `typing.Dict`/`typing.Tuple`, which is only available for 3.9 or newer version
- Use double quote inside fstring, which is only available for 3.12

Since the minimum required version for Cirq is 3.9, `tqec` should at least require python version 3.9 to work. So the problem is the features only available above 3.9. Do we need to forbid them or there is any solution that I'm not aware of?

**Comment by nelimee** [comment]
I did not take care of that at all, thanks for bringing that up. That would need a double-check, but I think that it should not be too hard to remove all the usage of post-3.9 features. In general, we should try to keep the library as accessible as possible, and this includes trying to support older versions of Python if possible.

**Comment by nelimee** [comment]
We set the baseline at Python 3.9 to stay as compatible as possible with old Python versions. `cirq` is only supporting `3.9` or above, so we cannot reasonably support earlier versions.

#124 probably should have close this issue, what do you think @inmzhang ?

**Comment by nelimee** [comment]
This is closed by #124. Feel free to re-open if you do not agree.
