### ISSUE TITLE
Top level imports

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#113]
Including imports at the top level of the package can be beneficial from the user's point of view, similar to what cirq has done in its [top-level](https://github.com/quantumlib/Cirq/blob/main/cirq-core/cirq/__init__.py).

What are your thoughts on this?

**Comment by nelimee** [comment]
Seems to be a good idea. 
Also I am in favour of explicit imports in library code, i.e., imports always start from `tqec` and go up to the module the object to be imported is defined with. Basically, for library code within `tqec`, never write `from tqec import CompositeTemplate` but use `from tqec.templates.composite import CompositeTemplate`.

**Comment by inmzhang** [comment]
> Also I am in favour of explicit imports in library code, i.e., imports always start from tqec and go up to the module the object to be imported is defined with.

To me, the top level imports can be used in: 
1. user codes 
2. notebook examples
3. tests

The library code should still insist on the absolute path imports.
