### ISSUE TITLE
Which minimum version of Python should we support?

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#123]
#121 is a good way for us to see if the code contains features that are incompatible with the current minimum supported Python version (`3.9`, because this is the minimum supported Python version of `cirq`).

The feature introduced in Python 3.10 with [PEP 604](https://peps.python.org/pep-0604/) introducing the possibility to use `|` on types (`Optional[int]` -> `int | None`) is one of the blocking point.

I would be in favour of bumping the minimum supported Python version to 3.10 for that reason. Even though I previously said that we should try to maintain as high compatibility as possible, I think that using `|` is way more readable for the code base.

One argument against bumping the version (and so in favour of replacing all the `|` by either `Optional[X]` or `Union[X, Y]`) is that `3.10` was released in Oct. 4, 2021, which is only a little bit more than 2 years ago, and Debian 11 Bullseye, which has not reached EOL, does not seem to support `3.10`.

Any opinion on that?

**Comment by inmzhang** [comment]
One solution in my mind is to support Python 3.9 and use `from __future__ import annotations` for newer type hints features.

**Comment by nelimee** [comment]
> One solution in my mind is to support Python 3.9 and use from __future__ import annotations for newer type hints features.

From the [`__future__`](https://docs.python.org/3/library/__future__.html) documentation, it seems like `annotations` is more about PEP 563 (see [Module Contents](https://docs.python.org/3/library/__future__.html#module-contents)) and is [not even required to be importable in `3.10`](https://docs.python.org/3/library/__future__.html#id2):
> `from __future__ import annotations` was previously scheduled to become mandatory in Python 3.10, but the Python Steering Council twice decided to delay the change ([announcement for Python 3.10](https://mail.python.org/archives/list/python-dev@python.org/message/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/); [announcement for Python 3.11](https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/)). No final decision has been made yet. See also [PEP 563](https://peps.python.org/pep-0563/) and [PEP 649](https://peps.python.org/pep-0649/).

Am I missing something?

**Comment by inmzhang** [comment]
You are right, it should not be a solution. Then I'm for setting 3.9 as the minimum required version. It's consistent with Cirq and there are still many Python 3.9 users as far as I can see.

**Comment by nelimee** [comment]
> As I delved into the documentation, I discovered that from __future__ import annotations does indeed enable support for the | operator when defining types. See [PEP604](https://peps.python.org/pep-0604/#change-only-pep-484-type-hints-to-accept-the-syntax-type1-type2).

Interesting! Let's do that an support `3.9` then. I'll open a PR in the next few hours.
