### ISSUE TITLE
Classes in `tqec.detectors.operation` could be improved

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#129]
There are several small issues with classes in `tqec.detectors.operation` that I found when trying to write tests for them. 

1. The attribute name `data` for the classes `RelativeMeasurementRecord`, `Observable` and `Detector` is too generic. Even tough this is mostly internal, I would prefer to read `relative_measurement_data` than a simple `data`.
2. `ShiftCoords` should check that it is initialised with "any number of coordinate offsets from 1 to 16" (per [`stim` SHIFT_COORDS gate documentation](https://github.com/quantumlib/Stim/blob/main/doc/gates.md#SHIFT_COORDS)).
3. The input data of `RelativeMeasurementRecord` is not checked. Several checks should/might be performed:
    1. Check that no `relative_measurement_offset` is `0` or positive (this is the role of `RelativeMeasurementData`).
    2. Check that the same `RelativeMeasurementData` is not repeated in the input `data` parameter.
    3. (maybe) enforce that the provided `time_coordinate`/`observable_index` for `Detector`/`Observable` should be non-negative.

The best would be to enforce these checks directly in the classes, and not in the factory functions, to avoid users bypassing them (knowingly or not) by using directly the classes.

**Comment by inmzhang** [comment]
> ShiftCoords should check that it is initialised with "any number of coordinate offsets from 1 to 16" (per [stim SHIFT_COORDS gate documentation](https://github.com/quantumlib/Stim/blob/main/doc/gates.md#SHIFT_COORDS)).

Actually, I do not see any cases where we will use shifts more than 3 dimensions. After all, the relative measurements restricted the detectors/observables' coordinates to be 3d.
