### ISSUE TITLE
Creating new plaquettes by copy-drag spawns extra plaquettes

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#13]
When I copy a plaquette by dragging, sometimes an extra plaquette appears, usually next to the new one, but sometimes on a different part of the tileset. [Example video](https://clipchamp.com/watch/NNNNwXJl3lF)

Mentioned in #12.

**Comment by smburdick** [comment]
I've been testing the latest commit (macOS / trackpad) and cannot copy-drag. Will post a video when that uploads to GDrive.

**Comment by smburdick** [comment]
For the above, need to set `this.eventMode = 'dynamic';` in the plaquette class. Will submit PR

**Comment by smburdick** [comment]
Rather than dragging by copy, it might be easier (both to use, and debug/program) to copy through a menu option.

1. Double click and select "Copy"
2. Mouse the cursor to where you want to place the plaquette. Placing can be disallowed, until a legal spot is selected
3. Click to copy the plaquette

**Comment by rryoung98** [comment]
Yes I was thinking of adding arrow keys @smburdick  looking forward to take a look at your PR :)

**Comment by smburdick** [comment]
<img width="859" alt="image" src="https://github.com/QCHackers/tqec/assets/16883876/3bf2c59d-b134-4376-b21a-238e128ae62f">
There are many additional logs statements that shouldn't be there just by mousing over the plaquettes after copying them.

**Comment by smburdick** [comment]
I believe this may be the culprit (in `makeExtensible()`)
```
		this.on('pointermove', this.onDragMove);
```
