### ISSUE TITLE
Re-organise backend files

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#134]
## Issue
The current file organisation in the `src/tqec` folder does not make a lot of sense.

<details><summary>Tree-view of the tqec backend files</summary><pre>
src/tqec
├── detectors
│   ├── measurement_map.py
│   ├── operation.py
│   └── transformer.py
├── display.py
├── enums.py
├── exceptions.py
├── generation
│   ├── circuit.py
│   ├── circuit_test.py
│   └── topology.py
├── noise_models
│   ├── after_clifford_depolarization.py
│   ├── after_reset_flip.py
│   ├── base.py
│   ├── before_measure_flip.py
│   ├── before_round_data_depolarization.py
│   ├── idle_qubits.py
│   ├── __init__.py
│   └── multi_qubit_gates.py
├── non_template_scaling
│   ├── animated_shape_display.py
│   ├── display_data.py
│   ├── __init__.py
│   └── non_template_scaling.py
├── plaquette
│   ├── library
│   │   ├── __init__.py
│   │   ├── xx.py
│   │   ├── xxxx.py
│   │   ├── zz.py
│   │   └── zzzz.py
│   ├── plaquette.py
│   ├── qubit.py
│   └── schedule.py
├── position.py
├── position_test.py
├── templates
│   ├── atomic
│   │   ├── rectangle.py
│   │   ├── rectangle_test.py
│   │   ├── square.py
│   │   └── square_test.py
│   ├── base.py
│   ├── composed.py
│   ├── constructions
│   │   ├── corner.py
│   │   └── qubit.py
│   ├── scale.py
│   └── scale_test.py
└── _version.py
</pre>
</details>

## Enhancement
It would be nice to re-organise the file hierarchy above to have a file organisation that makes more sense.

Example of files that, in my opinion, are not in the right place:
- `plaquette/schedule.py`,
- all the `detectors/` folder,
- `display.py` can likely go in the `templates/` folder,

Additionally, the `non_template_scaling` folder might not be relevant anymore. 

Any opinion on that? I would love to have the most feedback possible in order to do these changes only once.

**Comment by inmzhang** [comment]
The structure should definitely be refactored, though I don't have strong opinions for now. A few first impressions without deep thought:

- Those circuit related modules can go to the same folder, i.e. `plaquette/schedule.py`, `generation/circuit.py`. Even the modules in the `detectors` folder can also be placed in the same place as those.
- `templates/constructions` can be renamed as `composed` in contrast to `atomic`. These pre-defined templates can be placed in a folder like `templates/library` to make their intent more clear.

**Comment by nelimee** [comment]
So for the moment, the changes are basically:
- `templates/constructions/` -> `templates/library/`
- Create a `circuit` (idea for a better name? maybe `cirq`?) folder and move in it
  - `plaquette/schedule.py`
  - `generation/circuit.py` 
  - the content of `tqec/detectors/` 
- `display.py` -> `templates/display.py`
