### ISSUE TITLE
Task 3 Tile builder

### ISSUE THREAD

**Issue by rryoung98** [QCHackers/tqec#139]
@smburdick  do you know what Gian's GitHub is? I was going to update this myself to help me catch up and jump in with the current progress, but it might be better if he writes it up.

**Comment by smburdick** [comment]
> @smburdick  do you know what Gian's GitHub is? I was going to update this myself to help me catch up and jump in with the current progress, but it might be better if he writes it up.

https://github.com/giangiac

**Comment by smburdick** [comment]
We should add more details to the task flow to specify the user stories.
