### ISSUE TITLE
Specifying an `Observable` requires too much knowledge about implementation details

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#141]
## The issue
We have an [`Observable`](https://github.com/QCHackers/tqec/blob/09229fe45ede2827fa1718cf6fac6c3613254733/src/tqec/detectors/operation.py#L200) operation that can be used to add an observable to the quantum circuit generated. 

Creating correctly an observable currently requires to know implementation details. For example, because you can only create an observable by providing global qubit positions, you **need** to understand how the code is working in order to pick the right qubits.

## Expected improvement
It would be nice to be able to create an observable without needing any knowledge about the internal implementation details. 

I do not have any idea to make that easy at the time being, I am open to all suggestions.

**Comment by afowler** [comment]
Hi Adrien,

Some ideas below...

A final observable will be associated with an array of measurements, so
potentially fairly simple plaquettes. Is it possible to write a function
that detects whether a square template with just measurement plaquettes has
a well defined central vertical line or horizontal line of qubits? The idea
is to scalably choose the observable. A function that takes a final
measurement layer in, and H or V, and produces an observable. I believe
Stim is capable of detecting whether an observable is valid. It's ok if the
function fails to cope with some inputs.

I believe that ultimately to automate things we are going to need to be
able to detect such midlines.

When it comes to moving observables horizontally, and assuming we have well
defined midlines, it seems that templates with plaquettes with single
measurements as well as clean midlines would be a good starting point.
Moving observables from midline to midline would then typically mean
choosing to extend and contract along midlines, or using one half of the
checkerboard of plaquettes to move a midline operator sideways.

Happy to chat more 1-1 or in our next meeting.

Best,
Austin.

**Comment by Gistbatch** [comment]
I can have a look at this
