### ISSUE TITLE
Fix DNS configurations

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#146]
I reserved the domain `tqec.app` for us through CloudFlare, and am working out the DNS mappings through App Engine to make the service accessible through the concise domain.

That points to the backend service right now, which I will fix.

**Comment by vtomole** [comment]
Are you paying for hosting? If so, we probably want to pause that for now, keep the budget at $0, and have people run stuff locally until we get some type of external funding.

**Comment by afowler** [comment]
Thanks, if you need reimbursement, let me know, for minor things like this
I have a Google credit card.

**Comment by smburdick** [comment]
To be totally transparent:

* Hosting the service on App Engine and Cloudflare domain registration is costing me about $1 per month.
* I'm applying for a Unitary Fund microgrant to support myself as I contribute to TQEC. I'd like to support the service in the long term using that money as well.

In conclusion, if we start the scale up past the $20/month threshold, we should have a serious money discussion. Until then I am happy to support the main branch of the service on my own dime.
