### ISSUE TITLE
Push to App Engine when new update to main is performed

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#149]
**Is your feature request related to a problem? Please describe.**
Gcloud deployment is only done through CLI right now.

**Describe the solution you'd like**
When I merge to main, push to a beta endpoint and check it there. If everything checks it, push to prod endpoint.

**Describe alternatives you've considered**
This can be low-priority as we are still emerging into the MVP stage

**Additional context**
Use GitHub workflows for CI/CD.

**Comment by Gistbatch** [comment]
@smburdick, there is an unofficial GitHub integration for the app engine [repo](https://github.com/google-github-actions/deploy-appengine). This requires authenticating with the service, which you can only do as this is hosted on your private cloud.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
