### ISSUE TITLE
Persist unit cell

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#151]
**Is your feature request related to a problem? Please describe.**
When the page closes or reloads, user loses the unit cell they've created, in addition to any plaquettes they've made

**Describe the solution you'd like**
When the user creates a unit cell, it should be saved to their local storage, and when starting the app, be presented the option to load an existing unit cell.

- [x] When user specifies a unit cell, save it to the Redux store.
- [ ] When the app starts, check the Redux store. If there's a unit cell, offer to populate the grid, otherwise proceed as-is

Once this is implemented, we can move on to plaquettes, templates, circuits, etc.

These can also be saved to the backend, if/when user login info is stored and tied to constructed circuits.

**Describe alternatives you've considered**
Task 2 integration will proceed asynchronously to this. Once more circuit components are added, we can persist those as well.

**Comment by smburdick** [comment]
There can be a dedicated "Save" button, but saving it to the browser cache or the cloud (once logins are established) are fine. This will be especially important for templating.

**Comment by smburdick** [comment]
Need to define this user story a little better

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
