### ISSUE TITLE
Add undo/redo buttons

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#152]
**Is your feature request related to a problem? Please describe.**
When a creation/destruction action is taken, I'd like to be able to undo it, and if I change my mind before I've done something else, I'd like to be able to redo it.

**Describe the solution you'd like**
When an action is taken, I can click undo to reverse it.
When an action has been reversed, and no actions have been taken, I can click redo to restore the reversed action.

To implement this, simply use an actionStack. To undo, pop off an action onto the redoStack. To redo, pop the redoStack top and push it onto the actionStack.

**Additional context**
Discussed in 2/21 meeting.

**Comment by smburdick** [comment]
This opens up the possiblity for more than one redoStack: if the state that had an associated redo is returned to, we can recover it. But having two stacks keeps things simple.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
