### ISSUE TITLE
"Create Qubit Constellation" button does not work in mobile

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#161]
## Steps to reproduce the behavior:
Open https://tqec.app in a mobile browser.
Push "Create Qubit Constellation", it does nothing.

## Expected behavior
I think the mobile experience should be disabled. The app should detect if a mobile OS (iOS, iPadOS, Android) is in use, and if so, redirect to GitHub, or show a page with a link to a [mobile friendly!] doc explaining what TQEC is, with a link to github.

## Screenshots and MP4s

https://github.com/QCHackers/tqec/assets/16883876/cc86199a-2970-48b6-b680-673c95b96e40

## Browser info (please complete for frontend bugs):
 - iOS
 - Safari

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
