### ISSUE TITLE
Add mobile landing page

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#162]
**Is your feature request related to a problem? Please describe.**
Yes: #161 

**Describe the solution you'd like**
If I point to the app in mobile, I should see "What is TQEC?" and "GitHub repo" buttons, not the circuit editor

**Describe alternatives you've considered**
Building a mobile phone-friendly version should wait until we have everything we want working in the browser.

**Additional context**
Specifically redirect smartphone users

**Comment by nelimee** [comment]
> Specifically redirect smartphone users, definitely not desktop, and maybe tablets

For the moment I agree with the "nobody except computer-users". 
In the long run, ergonomics could be improved to also accommodate tablet users as I can see this as a real plus.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
