### ISSUE TITLE
Plaquette circuit expressed as Stim

### ISSUE THREAD

**Issue by giangiac** [QCHackers/tqec#167]
In the frontend v2, every type of plaquette is associated to the circuit measuring the stabilizer.
The circuit are currently represented via a ASCII art like:
```
X( 0, 0): ---------X--------------
                   |              
Z( 2, 0): ---------|---*----------
                   |   |          
A( 1, 1): |0> -H---*---*---H-- D~ 
          ___ ___ ___ ___ ___ ___ 
time ruler 0   1   2   3   4   5  
```

As we discussed in the weekly call, it would be great to express the circuit in the QASM language (in substitution of the ASCII art or, even better, in addition to it).

The circuit is drawn by the utility function `createCircuitAsciiArt()` in `<repo>/frontend_v2/src/workspace/circuit.js`.
It would be great having a similar one to create the equivalent QASM code.
If QASM and ASCII are complementary, we need functions to keep the representations in sync:
- from QASM to ASCII
- from ASCII to QASM
The former may be sufficient if we allow the user to modify the QASM code and use the ASCII art as a visual confirmation.

**Comment by smburdick** [comment]
I think the user data (plaquettes/qubits/circuits) can be mastered in JSON, and we can write a custom serializer that maps this JSON to OpenQASM. I don't think that's a bijective mapping, though.

**Comment by nelimee** [comment]
> I think the user data (plaquettes/qubits/circuits) can be mastered in JSON, and we can write a custom serializer that maps this JSON to OpenQASM. I don't think that's a bijective mapping, though.

For OpenQASM (`2.X` or `3.X`), the only thing that makes this mapping non-bijective is the fact that OpenQASM has no native support for qubit coordinates. With that exception, and knowing that the detectors will ultimately be computed automatically, I think that it should be fine, but I would need to implement it to be sure there is not a small detail I am missing that would break that.

Also, `Stim` file format supports natively both qubit coordinates and detectors.

**Comment by giangiac** [comment]
I will work on adding the stim code.

**Comment by giangiac** [comment]
> I will work on adding the stim code.

See PR https://github.com/QCHackers/tqec/pull/192
