### ISSUE TITLE
Multi-tab frontend and plaquette library

### ISSUE THREAD

**Issue by giangiac** [QCHackers/tqec#168]
Design a solution to add "tabs" to the frontend app.

The idea is that different tabs can be specialized to perform the TQEC tasks (see resources on Google's team) sequentially.
In case of the frontend this could be:
- TAB1:
  - define several plaquettes
  - associate a circuit / QASM code to every plaquette
  - save the plaquette in a library
- TAB2:
  - access the plaquette library and allow "drag and drop" of the plaquette on a large qubit array
  - possibility of representing the plaquette via a geometric form (square, triangle, semicircle, ...) or simply as an integer (its index from the library)

This feature concerns **ONLY** the reorganization of the HTML / JS code to allow for multiple tabs.
The content of each tab will be developed separately.

**Comment by smburdick** [comment]
@giangiac Just saw the discussion recording from yesterday. If you need any help merging the circuit editor/tutorial into the codebase, I'm happy to help.

**Comment by smburdick** [comment]
I think the user data (plaquettes/qubits/circuits) can be mastered in JSON, and we can write a custom serializer that maps this JSON to OpenQASM. I don't think that's a bijective mapping, though.

**Comment by giangiac** [comment]
@smburdick Your help would be great!
I tried to add "listeners" so that when the "tab1" and "tab2" buttons are clicked the corresponding content appears/disappears... but I was not able to make it work :-(

**Comment by smburdick** [comment]
> TAB2:
> access the plaquette library and allow "drag and drop" of the plaquette on a large qubit array

I personally think the plaquette library should be a drop-down on a single workspace, not a separate tab.

>possibility of representing the plaquette via a geometric form (square, triangle, semicircle, ...) or simply as an integer (its index from the library)

This can be specified on the plaquette menu.

**Comment by afowler** [comment]
Also, when plaquettes are stitched together, there may be identical gates
in neighboring plaquettes on identical qubits that should be interpreted as
only occurring once.

**Comment by smburdick** [comment]
> I believe there are two separate functionalities that we should implement the solutions "independently".

> The first one is the definition of a plaquette in terms of the physical qubits involved and the physical operations on them. This is what the current frontend is doing: creating a library of such plaquettes.

The frontend doesn't provide the ability to save plaquette/circuit designs to a library. It only allows creating them in the workspace and cloning them. The work for this is laid out in #189, and is part of the next milestone (the current one is being wrapped out rn)

> The second one is stitching the plaquettes together, taking them from the library. The same type of plaquette can be used multiple times and the tools need to understand that the same physical qubits might be shared among plaquettes.

> Also, when plaquettes are stitched together, there may be identical gates
in neighboring plaquettes on identical qubits that should be interpreted as
only occurring once.

Are we limited to stitching together plaquettes in the fashion of a standard surface code?

![image](https://github.com/QCHackers/tqec/assets/16883876/0979dd75-8c7c-4022-bb06-ced4b008a00c)

Either way, it would be nice for beginners to also provide the option to create a plain `d=3,5` surface code, like you can in Crumble.

**Comment by afowler** [comment]
The initial goal is to have plaquette footprints that are rectangular, with
the expectation that some of the qubits on the edges of that rectangle will
be shared with neighboring plaquettes. This means we are not strictly
limited to just the standard surface code.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
