### ISSUE TITLE
Enable import/export of local circuits

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#169]
**Is your feature request related to a problem? Please describe.**
I can't save my work and load it later.

**Describe the solution you'd like**
Options to save JSON circuit to local files, and load into the browser (including the unit cell)

**Describe alternatives you've considered**
Saving things on the cloud, which wouldn't be good for security-minded users.

Related -- #160

**Comment by smburdick** [comment]
Related: #170

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
