### ISSUE TITLE
Convert TQEC json format to OpenQASM/Stim

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#170]
**Is your feature request related to a problem? Please describe.**
User specifies plaquettes, qubits, circuits, etc. in a way conducive to TQEC. This work should be saved, and can be easily represented in JSON. But we'd also like to export to OpenQASM or Stim. That file may not be able to reconstruct the user's work, so we should still save the TQEC JSON file

**Describe the solution you'd like**
Provide to the user the ability to export their circuit to openqasm/stim

**Additional context**
[JSON specifications: ](https://github.com/QCHackers/tqec/tree/main/specification/schemas)

**Comment by nelimee** [comment]
Note that I do not think we should / can reasonably represent **all** the information in OpenQASM/Stim format.

In my opinion, we should just use the formats for what they were made for:
- OpenQASM/Stim to represent a quantum computation (i.e., quantum circuit),
- JSON to represent quite generic data.

The way I see it (that is also reflected in the tentative JSON specification) is that only the quantum circuit (not the qubits not the detectors) will be represented as OpenQASM/Stim, the other information being encoded in JSON.

**Comment by nelimee** [comment]
Then I misunderstood your message, my bad, I am sorry 👍
