### ISSUE TITLE
Use reactflow to specify UI components

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#176]
**Is your feature request related to a problem? Please describe.**
The current UI has a lot of nested `eventListener` assignments/destructors to define the control flow. To make our UI more extensible (and easier to understand), add a control-flow graph to define UI components.

**Describe the solution you'd like**
Add https://reactflow.dev/ to the code base. The graph can be mastered in Redux, thus accessible to any class, but shouldn't necessarily be modifiable.

**Describe alternatives you've considered**
Leaving it as-is for now for the prototype is fine, but as we add more UI components, let's abstract more.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
