### ISSUE TITLE
Save tile set as Stim file

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#18]
https://github.com/quantumlib/Stim/blob/main/doc/file_format_stim_circuit.md

**Comment by smburdick** [comment]
Do we want to be able to save the circuit that the user created on the frontend to a file? If so, we can add a button on the frontend, which could invoke a function on the backend (passing the current circuit as a parameter), and return a stim file to the browser.

**Comment by nelimee** [comment]
Yes I agree, but this scheme does not require the UI part to know about the structure of a Stim file, only to know that it is a textual file. Am I missing something?

**Comment by smburdick** [comment]
Right, the UI can be totally agnostic of the file structure, it would just have to invoke the Python backend to get the file back

**Comment by smburdick** [comment]
I'm pretty sure this is Task 11.

**Comment by nelimee** [comment]
I am still having hard times understanding what this issue is about. The title is about "tile set", but it seems to me that you are rather referring to the final Stim files.

Also, having a Stim file does not equate task 11. For task 11, we still have to simulate the different Stim files and perform the graph. This is made easy by the `sinter` package, but it is more than simply "getting the Stim files".

**Comment by smburdick** [comment]
My terminology may be off here. By "tile set", I mean the set of plaquettes the user has made in the frontend. My impression is that these plaquettes and qubits (as well as templates, which we don't have in the UI yet) will need to be communicated to the backend, which will perform some work on the input to generate a circuit or other object that is meaningful to the user, and return that to them.

My most recent pull requests #40 and #41 establish this communication in an early stage -- crucially, the real processing on the backend is missing, (the input is returned as the output by the backend, as a placeholder) as we appear to need templates as well to construct a circuit.

**Comment by nelimee** [comment]
As a note, I tried to provide a first version of what the backend would need as input to do its job. This can be found [here](https://github.com/QCHackers/tqec/tree/main/specification/schemas) (and I will modify it in the next few days).

**Comment by smburdick** [comment]
@nelimee Awesome! Thank you for making those specifications. Once #43 is finalized, I will update the serialization in #41

**Comment by smburdick** [comment]
Updated #41 to incorporate the current specs

**Comment by smburdick** [comment]
This is being addressed in #192

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
