### ISSUE TITLE
Align circuit ascii time ruler

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#184]
## Steps to reproduce the behavior:
1. Create a circuit, check the console once it is finished.

![image](https://github.com/QCHackers/tqec/assets/16883876/ccd92f11-18fc-4f87-b16a-5de2a84dedba)

## Expected behavior
Every line should line up. Consider a non-ascii format, though having ascii is good for making it quickly copiable elsewhere.

**Comment by smburdick** [comment]
@giangiac Are you able to address this one in #192 as well?

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
