### ISSUE TITLE
Change template specification to footprint specification

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#186]
## Describe the bug
I shouldn't have to specify a template before I specify a plaquette.

## Steps to reproduce the behavior:
1. Specify unit cell
1. I must specify template, when I should be able to specify a plaquette right away.

## Expected behavior
Once the qubits have populated, I should be able to start clicking them and when 3+ have been clicked, specify a plaquette.

## Screenshots and MP4s
![image](https://github.com/QCHackers/tqec/assets/16883876/35941c6c-1fff-49a9-b481-e2c556c32992)

## Other context:
From discussions with @afowler .

## Coding task

Bypass the `template` functions: hoist plaquette addition into the control flow function.

**Comment by afowler** [comment]
There might be another way to use the existing behavior, namely to specify
the plaquette footprint. Every plaquette should have the same footprint.

In our usual architecture the footprint is a square containing 5 qubits,
and all plaquettes would be defined on a subset of this.

**Comment by smburdick** [comment]
@afowler 

> There might be another way to use the existing behavior,

I think templating should be have more granularity than how it is now, which is a connected rectangular subset of the qubits. We can keep the template class, and it will have to change to meet the needs of tasks 4 and 5.

> namely to specify the plaquette footprint. Every plaquette should have the same footprint.  In our usual architecture the footprint is a square containing 5 qubits, and all plaquettes would be defined on a subset of this.

We should have a "Create square plaquette" and "create triangular plaquette" buttons, which can be recolored, rotated, translated, etc, and users can define circuits on top of them [Task 3]

**Comment by afowler** [comment]
In my opinion you should start without the ability to rotate plaquettes, I
think that will be quite hard to do in general. I'm ok with having to build
a plaquette for each orientation, particularly since the timing of the
gates will be different for different orientations.

**Comment by smburdick** [comment]
> In my opinion you should start without the ability to rotate plaquettes, I
think that will be quite hard to do in general. 

@afowler I feel that depends on what angles you can rotate by. Right now, it's only 90 degrees. What other options do we want to provide?

**Comment by afowler** [comment]
I don't think we should even provide that in the beginning as I don't think
rotating will be very helpful.

**Comment by smburdick** [comment]
Going to close this one out, and move the rotation and other options to another issue.

**Comment by smburdick** [comment]
Will be presented on Wednesday meeting.
