### ISSUE TITLE
Save plaquette data to plaquette libary

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#189]
User should be able to select "Save plaquette" from its drop-down; clicking it will save the plaquette's shape, color, rotation, and circuit selection to the 

**Describe the solution you'd like**
- [ ] Implement a full `serialized()` function 
- [ ] Save JSON string to Redux store
- [ ] On start, get the plaquette templates from the Redux store.

**Additional context**
Tasks 4/5.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
