### ISSUE TITLE
Qubits should not be clickable (when my mouse hovers over them, the pointer hand should not appear). 

### ISSUE THREAD

**Issue by rryoung98** [QCHackers/tqec#194]
Before this point, qubits should not be clickable (when my mouse hovers over them, the Mickey Mouse hand should not appear). Can we change that?

_Originally posted by @smburdick in https://github.com/QCHackers/tqec/pull/193#discussion_r1523712320_

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
