### ISSUE TITLE
Implement automatic detector computation

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#199]
**Is your feature request related to a problem? Please describe.**
Currently, the `tqec` library requires users to explicitly implement the detectors. To ease that process, detectors are automatically included in `Plaquette` instances for the "default" situation, when that makes sense. But this way of adding detector is not optimal:
- the "default" detectors have been chosen arbitrarily, and are not a good fit for all possible codes,
- requiring users to explicitly annotate detectors should remain a possibility, but is a tedious and error-prone process,
- there are ways to find detectors automatically.

**Describe the solution you'd like**
We need to provide a way for users to automatically add detectors. This should be opt-in, as the automatic computation of detectors will likely, at least in the beginning, be driven by heuristics (i.e., not always correct/exhaustive), and because we want the library to provide the most control possible to the users that require it.

**Describe alternatives you've considered**
For the moment, I am not sure how this should be implemented. I have a theoretical reformulation that works generally, but that is not convenient to compute and may be made more efficient. We also have very localised information: propagated Paulis are, in the current setup in which we only consider surface codes, very much local and cannot spread globally (in the spatial dimension). There might be a way to use that feature by considering the QEC at the plaquette level, before generating the actual circuit.

Finally, we will likely require another abstraction: "layer". It seems reasonable, at the moment and (again) in the setup we are considering, that a QEC is composed of a sequence of layers, each following the scheme:
- `0` or `1` Moment (in the `cirq` sense) of reset,
- `k` Moments of computation with Clifford gates,
- `0` or `1` Moment of measurement.

**Additional context**
- [@inmzhang answer in a PR](https://github.com/QCHackers/tqec/pull/100#issuecomment-1952002691)
- [Inplace Access to the Surface Code Y Basis (Appendix C)](https://arxiv.org/abs/2302.07395)

**Comment by inmzhang** [comment]
I'll start working on this when I have time. As a starting point, I will try to implement exactly what Austin proposed, which I think should be sufficient for the near-term goal.

**Comment by nelimee** [comment]
@inmzhang any update on that issue?

**Comment by inmzhang** [comment]
Sorry for taking such a long time. I have done most of the work except for the anticommute grouping and several edge cases. Hopefully I'll complete the remaining stuff and start iterating on the design in this week.
