### ISSUE TITLE
Specifying a plaquette's stabilizers

### ISSUE THREAD

**Issue by eddieschoute** [QCHackers/tqec#200]
**Is your feature request related to a problem? Please describe.**
Specifying a canonical circuit for a plaquette seems counter-intuitive. I'd expect the qubits to be physical qubits and the ancillas to be implicit. So then I have to go back and make an explicit ancilla qubit so that I can specify my canonical circuit.

**Describe the solution you'd like**
A plaquette should have associated stabilizers for each data qubit. A circuit can then be generated that uses an ancilla (that is not represented in the UI) to measure the stabilizer. It could then also easily allow for visualization of the stabilizers along each plaquette, including Y.

**Describe alternatives you've considered**
Visualizing the stabilizer circuit on the plaquette, but that seems too messy.

**Additional context**
This would require some new interface to specify stabilizers, but I think it could be simpler than it is right now. Moreover, I think visualizing it will be easier.

**Comment by afowler** [comment]
This layer of software must allow the user to specify everything, every
qubit, every gate, full control. At the moment to focus should be on
permitting this level of control with minimum pain rather than reducing in
any way the level of control of the details.

I personally don't think you can avoid the need to explicitly specify
ancilla qubits.

**Comment by eddieschoute** [comment]
Indeed, if there is a need to fully specify what a plaquette means then there is no simplification possible but to explicitly specify the circuit. However, it may be possible to hide ancillas in the UI and only make them explicit when specifying the "plaquette circuit" since these are not necessarily long-lived qubits. Or would you also want ancillas to have a physical place on the diagram UI?

**Comment by afowler** [comment]
My preference would be for the ancilla to be explicitly visible. It is a
real qubit and every qubit in a quantum computer is important.

There are also situations where ancilla and data qubits exchange roles. I
do not think hiding any of the qubits is the right thing to do.

**Comment by eddieschoute** [comment]
Okay, that seems very reasonable. But that does imply we need much more powerful tools to specify the circuit of a plaquette. Maybe the "common" case of stabilizer measurements could be supported in the UI but the full tools would need plaquette circuits to be specified in some programming language (e.g. a Cirq circuit).

**Comment by eddieschoute** [comment]
Closing this since the topic shifted quite a bit
