### ISSUE TITLE
Click-cycle to specify qubits

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#201]
**Is your feature request related to a problem? Please describe.**
The current way of specifying the quantum circuit in the main `frontend` is to first click on all the ancillas, then click on all the qubits that should be touched by a `CX` gate, and then click on those that should be touched by a `CZ` gate. This has several drawbacks in my opinion:
- it is not intuitive for me,
- I do not see an intuitive enough way of correcting a potential miss-click from the user,

**Describe the solution you'd like**
The way this step is addressed in `frontend_v2`/`tutorial` is better in my opinion. The user clicks on qubits, and each click on the qubit make it cycle through the "state" `A -> X (-> Y) -> Z` that represent the Pauli operator that should be measured on that qubit. The fact that the "state" is cycling makes correcting a miss-click super easy (3 clicks maximum) and quite intuitive (in my subjective opinion).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by afowler** [comment]
+1 for making this change

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
