### ISSUE TITLE
Fix reset and measurement gates being wrongly applied when moving

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#202]
The initial comments on #100 raised a few very valid points that are not fixed yet. This issue document one of them.

Relevant part of the original comment:

> - The glue between different layers remains a cumbersome aspect. Maybe we can use some strategy pattern to specify how to merge /rewrite operations at the temporal boundaries when integrating different layers. For example, we can define a strategy to eliminate the reset operations for the already-in-use qubits when stacking an initialization layer onto a memory layer.
> 
> _Originally posted by @inmzhang in https://github.com/QCHackers/tqec/pull/100#pullrequestreview-1887608426_

**Is your feature request related to a problem? Please describe.**
Moving a logical qubit requires a few manipulation on `Plaquette` instances. Let's take the example below
![move_qubit_along_z](https://github.com/QCHackers/tqec/assets/12374487/9a76cc18-bf86-4991-ba8a-471e8c6f89a5)

Going from `1` to `2` has no issue. `Plaquette` instances that are used in `2` automatically reset their syndrome qubit by default
https://github.com/QCHackers/tqec/blob/47cb5e9712ab02959df9e2ce552cf8c663a2b110/src/tqec/plaquette/library/utils/pauli.py#L10-L56
but this reset gate can be tagged to be merged automatically afterwards like
https://github.com/QCHackers/tqec/blob/47cb5e9712ab02959df9e2ce552cf8c663a2b110/src/tqec/plaquette/library/measurement.py#L29

> [!NOTE]  
> Turns out the reset is not tagged, a follow-up issue will be opened to address that.

Changing `2` into `3` is a little bit more challenging, because we need to apply [initialisation plaquettes](https://github.com/QCHackers/tqec/blob/main/src/tqec/plaquette/library/initialisation.py) to the qubits to the right (in the example above), but we also need to avoid resetting the data qubits highlighted in blue.

Finally, changing `3` into `4` has the same issue, but with measurements: we need to apply the [measurement plaquettes](https://github.com/QCHackers/tqec/blob/main/src/tqec/plaquette/library/measurement.py) but also need to make sure that the data qubits highlighted in blue are not measured, as they are still used.

**Describe the solution you'd like**
I have no preference, as long as we are able to make that work, if possible elegantly, I am fine with the solution.

**Describe alternatives you've considered**
None of the following alternatives have been tested yet:
1. As noted in the comment cited at the beginning of this issue, maybe find a clever way to remove reset and measurement gates in some conditions. My main concern here is that I think this will be tricky to get predictable, easy to explain to a potential user, and right in all cases.
2. We may also try to make the initialisation and measurement plaquettes aware of that kind of situations (e.g., adding a `PlaquetteSide` argument somewhere that would be either the side of the plaquette that should be kept or the one that should be reset/measured).

**Comment by nelimee** [comment]
Note that potential solution number 2 above is not enough: we do not want to have to re-define specific `Template` instances to be able to apply different plaquettes as this is the main pain point found by implementing the qubit movement in #81 and #100. 

This additional restriction leaves us with very little freedom to implement something, and I can only see option 1 (automatically removing the operations in some way) if we want to avoid creating a (or several) new `Template` and `Plaquette` instances.

**Comment by smburdick** [comment]
I'd like to help out with the backend some more, so I can look into this.

**Comment by nelimee** [comment]
One more piece that might be important for this one: we can consider logical qubits to have assigned positions on the physical qubit grid. 
![Quick sheets - page 67](https://github.com/QCHackers/tqec/assets/12374487/728fef63-62da-449e-828b-bc267d63eadc)
In the grid above, `Template` instances are drawn in blue, and it is reasonable to limit ourselves to logical qubits that can only be within a red square. In other words, logical qubits are arranged on a grid.

Feel free to discuss what you plan to do here, both @inmzhang and myself have implemented the qubit movement and so we might be able to see if there is any shortcoming early.

**Comment by nelimee** [comment]
@smburdick any update on that issue?

**Comment by afowler** [comment]
Sam is out this week, can anyone else help?

**Comment by nelimee** [comment]
> Sam is out this week, can anyone else help?

Let's wait for Sam on that. I can start hacking, but I do not want to re-do things that Sam already did on his side without pushing online, and as he assigned to this issue he should have the priority.

**Comment by nelimee** [comment]
@smburdick have you started to look at that issue on your side? 

If not, I am thinking about coming back to it and try to find a reasonable solution to this long-standing issue that is currently blocking most of the interesting developments. 

If you did think about it / write code to solve it, could you share your work?

**Comment by nelimee** [comment]
> @nelimee I haven't had time recently due to my personal life, and being more focused on the frontend. I don't know if I'll have time to in the next couple of weeks.

If this is fine for you, I will assign myself to that issue then. Thanks for answering :)

**Comment by nelimee** [comment]
Closing this issue as we are changing the way we think about movement. Rather than a movement, it is a merge of 2 logical patches.
