### ISSUE TITLE
Improve the Wiki / Keep it up to Date

### ISSUE THREAD

**Issue by Gistbatch** [QCHackers/tqec#207]
**Is your feature request related to a problem? Please describe.**
Sam started a Wiki for this repository. We should make a group effort to keep it updated.

**Describe the solution you'd like**
Possibly as part of the "definition of done", when merging a PR make sure that the wiki is updated.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by smburdick** [comment]
My idea for the documentation is for it to grow organically. If you feel something is needed, feel free to add even just a short paragraph. I think just adding one small piece at a time is the most productive and proactive approach.

**Comment by nelimee** [comment]
Once the recording from yesterday is available, I will update the FAQ with the questions, a short textual answer, and a link to the full answer in video. We can probably do that for the following meeting(s) as well.
