### ISSUE TITLE
Suggestion: separate TQEC frontend/backend into submodules

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#21]
Since `tqec` (Python backend) and `tqec-js` (React frontend) are becoming large projects in their own right, it'd make sense to separate them into their own repositories, and combine them back into this repository as submodules.

**Comment by vtomole** [comment]
Different repositories will make it harder to coordinate the project. Different issue lists e.t.c. A monorepo the way Cirq does it makes things easier communication-wise.
