### ISSUE TITLE
Check/Fix GitHub pages

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#221]
## Describe the bug
#211 should have introduced automatic deployment to GitHub Pages. I cannot see the website yet, https://qchackers.github.io/ returns a 404. 

## Steps to reproduce the behavior:
1. Open https://qchackers.github.io/
2. Enjoy the error 404

## Expected behavior
Not a 404

## Additional context
This might be due to delays in the setup of GitHub pages (DNS / other things). This might also be due to a misconfiguration on my side. This issue is open to remind me to check if the pages are working as expected in a few hours / days.

**Comment by nelimee** [comment]
Turns out the correct URL is https://qchackers.github.io/tqec/. I will leave that issue open to think about editing the README and other places to include that URL.

**Comment by smburdick** [comment]
+1 for setting this up!
