### ISSUE TITLE
[Rev. Task 2] Copy constellation qubits from the footprint, not the 

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#225]
**Is your feature request related to a problem? Please describe.**
When I specify the footprint, it should copy the qubits 

**Describe the solution you'd like**
Instead of copying from the top-left corner, copy outward from where the footprint was specified

**Describe alternatives you've considered**
The current implementation copies from the top-right according to the footprint, when we should be copying outward (like a spiral) from the current footprint.

**Additional context**
Refer to the revisited task flow.

**Comment by afowler** [comment]
To be clear, I don't think you have to do a spiral copy. You just need to
make sure that when you copy, however you wish to do this copy, left to
right top to bottom, or any other method, that qubits placed do not land on
top of one another. This check should be done before you allow the user to
save the footprint. Once a valid footprint has been saved, you can copy it
across the screen however you like.

**Comment by smburdick** [comment]
In that case, I will close this issue and stick with #219 .
