### ISSUE TITLE
Re-implement `Set.intersection` for Firefox/Safari compatibility

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#230]
## Describe the bug
The app only supports Chrome due to its use of `Set.intersection` to populate the workspace with qubits.

## Steps to reproduce the behavior:
1. Go to https://tqec.app in Firefox or Safari
2. Create a footprint and constellation
3. Compare behavior with Chrome

## Expected behavior
Same functionality, just custom-implemented for our use case to support other browsers.

## Browser info (please complete for frontend bugs):
 - OS: MacOS M1
 - Browser: Safari, Firefox

## Additional context
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/intersection

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
