### ISSUE TITLE
Footprint doesn't align with qubits

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#236]
## Describe the bug
The footprint doesn't always align with the specified architecture after it's used to populate the qubits.

## Steps to reproduce the behavior:
Specify a 2x2 footprint with the top-left corner at coordinates `(300,100)`.

## Expected behavior
The qubits should always align with what's in the footprint.

## Screenshots and MP4s
![ezgif-1-1f6eb826fb](https://github.com/QCHackers/tqec/assets/16883876/3265156c-60c8-4b92-a0ef-6827812c6b7b)

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
