### ISSUE TITLE
Implement more plaquettes in the plaquette library

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#246]
**Is your feature request related to a problem? Please describe.**
Currently, the plaquette library is containing a few basic plaquette instances. But these plaquettes are not sufficient to implement at least a logical CNOT between two logical qubits.

**Describe the solution you'd like**
All the plaquettes used in [the revisited task flow](https://docs.google.com/presentation/d/1ejwDlIBEOo3w13n6MvqvKJ4woBwvubXJhTSOuf-YGgI/edit?usp=sharing) should be implemented.

**Describe alternatives you've considered**
#202 is an alternative that would allow the definition of less plaquettes, but would introduce rules to automatically remove reset/measurement gates that may not be clear.

**Comment by KabirDubey** [comment]
More plaquettes are still needed, but this will be handled in separate issues/PRs such as #345. See `PlaquetteLibrary` in #346.
