### ISSUE TITLE
List all valid observables from a ZX diagram

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#270]
**Is your feature request related to a problem? Please describe.**
We currently have no way to automatically discover observable. 

**Describe the solution you'd like**
This will be a two-stage process:

1. Create a function that takes a ZX diagram such as 
    ![Image](https://github.com/user-attachments/assets/28b03fa1-4869-4366-adc0-f5b6e28ee6b6)
    as input and returns a list of all the observable that can be considered valid. This amounts to a graph exploration following some exploration rules that have been detailed in our previous meetings and in some presentation.
2. _(separate issue: #271)_ Create a function that takes the data obtained in 1 and the topological computation as input and returns a **scalable** observable.

This issue is only about 1. 

The ZX diagram could be represented by a `networkx.Graph` with some annotations (e.g., is the node black or white?), but if another solution is found to be better then let's use it!

Note that the return format is not defined yet, you will have to think about it and discuss with people on #271 and #272 to be sure that the return format of point 1 is usable in 2.

**Comment by inmzhang** [comment]
Question: how to choose the generating set of the valid observable?

As the deterministic observables are just a way to verifying the underlying (part of)stabilizer flows represented by the block structure, there are some freedom to choose the generating set of the observable. For example, in the CNOT gate shown above, we can choose between "1", "4" and mirrored "h" shape observables. And two of them should be enough. Is there any general idea to choose the independent generating set to track? Austin, could you elaborate on this?@afowler

**Comment by afowler** [comment]
For the moment I'd like to keep all unique (not just generating)
observables. I think they are all (at least initially) worthy of simulation
and study.

Best,
Austin.
