### ISSUE TITLE
Construct scalable observable

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#271]
**Is your feature request related to a problem? Please describe.**
#270 is concerned about finding all valid observable in a graph, this issue is about transforming the obtained graph information to a data-structure that can represent an observable (i.e., a list of measurements) that can scale with the templates.

**Describe the solution you'd like**
As explained in #270, the input for the function created to solve this issue is not fixed and will have to be discussed and agreed upon with people working on #270. 
The output format is not fixed either and will need to be easy to use for quantum circuit generation. This might require some changes in the current circuit-generation code, which is not a problem per se, but an output format that require little to no change in the current code will be preferred.

**Comment by inmzhang** [comment]
Closed by mistake. I'll work on this.
