### ISSUE TITLE
Check formatting and linting on CI

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#288]
**Is your feature request related to a problem? Please describe.**
Currently, formatting and linting are not automatically checked and are the responsibility of each developer. 

**Describe the solution you'd like**
I would be nice to check code formatting and linting automatically, either in CI on each PR and block the PR if formatting and linting are not correct or using something like [`pre-commit`](https://pre-commit.com/).

**Additional context**
I would be in favour of using `ruff` and the already packaged https://github.com/astral-sh/ruff-pre-commit, but this is up to discussion. What is the opinion of the Python developers here?

**Comment by inmzhang** [comment]
`ruff` +1
