### ISSUE TITLE
`BlockGraph` -> `Computation`

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#294]
**Is your feature request related to a problem? Please describe.**
There is currently a missing piece in the chain of data-structures we use to go from a `.dae` file to a `stim` circuit: we cannot build a `Computation` instance from a `BlockGraph` instance. 

**Describe the solution you'd like**
It is necessary for the tool to be able to build a `Computation` from a `BlockGraph` instance. 

**Additional context**
It may be interesting for #287 to change the data stored in the `Computation` data-structure and also include a graph-like representation of the blocks, to avoid having to re-compute block neighbouring information when calling `Computation.to_circuit`. As such, in accordance with the person on #287, it is entirely possible to re-write the `Computation` class from scratch.

**Comment by Gistbatch** [comment]
I'll have a look at this!
