### ISSUE TITLE
Improve the plaquette creation UI

### ISSUE THREAD

**Issue by rryoung98** [QCHackers/tqec#30]
The creating a plaquette functionality at the moment involves dragging the closest plaquette up down left and right. 

However, this functionality creates a buggy experience where plaquettes will pop up when the (deltaX-initialposition) is large enough and the mouse was recently clicked but not pressed down.

We want to remove to improve this by perhaps using arrow keys or another method that is more definite.

**Comment by smburdick** [comment]
In working on #24 , I created a button interface on the control panel for spawning new plaquettes.

**Comment by smburdick** [comment]
@rryoung98 Do we still want to work on this, or backlog it?

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
