### ISSUE TITLE
Create a small CLI to automatically generate circuits from a .dae file

### ISSUE THREAD

**Issue by Gistbatch** [QCHackers/tqec#301]
**Is your feature request related to a problem? Please describe.**
The simplest way of interacting with our tool is a CLI interface.

**Describe the solution you'd like**
In the best case we would have something like: `tqec generate-circuits -i cx.dae -o cx.stim`

**Describe alternatives you've considered**
As alternatives, we can still use the jupyter notebooks, but I find that could be more convenient.
We could also eventually add this to the front end. 

**Additional context**
With #298 and #300, we will have parts of this already; we have to piece it together.
We can use this to discuss the potential interface; implementation should be rather easy.

**Comment by nelimee** [comment]
Two notes on that:
- we can have only one entry-point script named `tqec` with [subcommands](https://docs.python.org/3/library/argparse.html#sub-commands) or multiple scripts that would preferably share a common prefix (likely `tqec_`) for discoverability purpose. 
- Once #298 is merged, we will be able to generate `stim` files without detectors and observables. More work needs to be done to include detectors (I am still thinking about the best way of doing that) and observables.
