### ISSUE TITLE
Dev Installation: `pycryptosat` wheel, `pre-commit` requirement

### ISSUE THREAD

**Issue by KabirDubey** [QCHackers/tqec#311]
Installing the developer requirements for the package fails for `pycryptosat` and `pre-commit`. In a clean virtual environment the command `python -m pip install ".[dev]"` yields the error `ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycryptosat)`. The subsequent command `pre-commit install` returns `command not found`. Doing `pip install pre-commit` allows the command to be recognized, but`pre-commit` should of already been installed when we installed the dev requirements. 

Happy to assign myself to look closer into this, but would need some guidance on these installation tools.

## Steps to reproduce the behavior: 
1. `python -m venv venv-test`
2. `source venv-test/bin/activate`
3. `python -m pip install ".[dev]"`
4. `pre-commit install`

## Full error message for `pycryptosat`

```
Building wheel for pycryptosat (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycryptosat (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing src/pycryptosat.egg-info/PKG-INFO
      writing dependency_links to src/pycryptosat.egg-info/dependency_links.txt
      writing top-level names to src/pycryptosat.egg-info/top_level.txt
      reading manifest file 'src/pycryptosat.egg-info/SOURCES.txt'
      adding license file 'LICENSE.txt'
      adding license file 'AUTHORS'
      writing manifest file 'src/pycryptosat.egg-info/SOURCES.txt'
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-312
      creating build/lib.macosx-11.0-arm64-cpython-312/msvc
      copying src/msvc/stdint.h -> build/lib.macosx-11.0-arm64-cpython-312/msvc
      creating build/lib.macosx-11.0-arm64-cpython-312/picosat
      copying src/picosat/pico_config.h -> build/lib.macosx-11.0-arm64-cpython-312/picosat
      copying src/picosat/picosat.c -> build/lib.macosx-11.0-arm64-cpython-312/picosat
      copying src/picosat/picosat.h -> build/lib.macosx-11.0-arm64-cpython-312/picosat
      copying src/picosat/version.c -> build/lib.macosx-11.0-arm64-cpython-312/picosat
      creating build/lib.macosx-11.0-arm64-cpython-312/oracle
      copying src/oracle/oracle.cpp -> build/lib.macosx-11.0-arm64-cpython-312/oracle
      copying src/oracle/oracle.h -> build/lib.macosx-11.0-arm64-cpython-312/oracle
      copying src/oracle/utils.h -> build/lib.macosx-11.0-arm64-cpython-312/oracle
      running build_clib
      building 'picosatlib' library
      creating build/temp.macosx-11.0-arm64-cpython-312
      creating build/temp.macosx-11.0-arm64-cpython-312/src
      creating build/temp.macosx-11.0-arm64-cpython-312/src/picosat
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -arch arm64 -mmacosx-version-min=11.0 -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-undef-prefix -fPIC -Werror=unguarded-availability-new -Isrc/picosat/ -c src/picosat/picosat.c -o build/temp.macosx-11.0-arm64-cpython-312/src/picosat/picosat.o
      src/picosat/picosat.c:2282:50: warning: variable 'count_resolved' set but not used [-Wunused-but-set-variable]
        unsigned num_true, num_undef, num_false, size, count_resolved;
                                                       ^
      src/picosat/picosat.c:5334:12: warning: variable 'collect' set but not used [-Wunused-but-set-variable]
        unsigned collect, delta;
                 ^
      src/picosat/picosat.c:6467:12: warning: variable 'num_non_false' set but not used [-Wunused-but-set-variable]
        unsigned num_non_false;
                 ^
      3 warnings generated.
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -arch arm64 -mmacosx-version-min=11.0 -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-undef-prefix -fPIC -Werror=unguarded-availability-new -Isrc/picosat/ -c src/picosat/version.c -o build/temp.macosx-11.0-arm64-cpython-312/src/picosat/version.o
      /var/folders/m_/cksx93ys47x4621g0zbw_m4m0000gn/T/tmpsc7lpqit/tools/llvm/bin/llvm-ar rcs build/temp.macosx-11.0-arm64-cpython-312/libpicosatlib.a build/temp.macosx-11.0-arm64-cpython-312/src/picosat/picosat.o build/temp.macosx-11.0-arm64-cpython-312/src/picosat/version.o
      error: command '/var/folders/m_/cksx93ys47x4621g0zbw_m4m0000gn/T/tmpsc7lpqit/tools/llvm/bin/llvm-ar' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycryptosat
Successfully built tqec
Failed to build pycryptosat
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycryptosat)
```

## Python dependency versions (please complete for backend bugs)

Run `pip freeze` and put the output in the `<details>` element below.

<details>
cfgv==3.4.0
distlib==0.3.8
filelock==3.15.4
identify==2.6.0
nodeenv==1.9.1
platformdirs==4.2.2
pre-commit==3.8.0
PyYAML==6.0.2
virtualenv==20.26.3
</details>

**Comment by Gistbatch** [comment]
Thanks for the input. Two quick question which OS are you on and wich python version are you using?

**Comment by KabirDubey** [comment]
Thank you, Philipp. My OS is Mac OS Sonoma 14.6.1 and python version is `Python 3.12.5`. I followed your installation (only difference is cloned from HTTPS rather than SSH) and ran into the same errors. Will try again with your python version.

**Comment by nelimee** [comment]
This is interesting and valuable input. The problem is not Python version, the problem is about your (or rather your computer / pip) ability to compile the [C++ library](https://github.com/msoos/cryptominisat) used by `pycryptosat`.

[Pre-compiled packages](https://pypi.org/project/pycryptosat/#files) are available for any GNU/Linux distribution and for all the Python versions `tqec` support, so the compilation do not have to happen locally at installation. But you do not have a GNU/Linux distribution, so nothing is pre-compiled for you, so `pip` ends up using the long road: compiling the C++ library, then installing the Python package from sources.

According to https://github.com/numpy/numpy/issues/17777, it might ends up working by simply executing
```sh
export AR=/usr/bin/ar
```
**before** the pip install command. The correct fix would be to install the missing binary `llvm-ar`, but the `llvm` present on MacOs is an Apple-specific version that might not include that specific binary.

**Comment by KabirDubey** [comment]
I see. That is interesting! I tried again with `Python 3.10.12` and it made no difference. As @nelimee suggested, I reset my `AR` shell variable after I created my virtual environment but before I `pip` installed anything and the installation is successful (about 30 seconds longer though). Closing the issue, thanks everyone.

**Comment by nelimee** [comment]
I think the issue can be re-opened in order for us to think about that and add instructions to the installation procedure for Windows / MacOS users that will eventually encounter that exact same issue.

TODO: add the `export AR=/usr/bin/ar` solution somewhere in the installation procedure.

**Comment by inmzhang** [comment]
Add MacOS and Windows in the `ci.yml` might help with this type of issues, while some machine/environment specific problems can still be tricky to test.

**Comment by nelimee** [comment]
> Add MacOS and Windows in the `ci.yml` might help with this type of issues, while some machine/environment specific problems can still be tricky to test.

The only thing that makes me cautious with that is the cost. Windows CI runs have a multiplier of 2 on the CI minutes used (if the job took 4 minutes, 8 are billed) and MacOS have a multiplier of 10. See https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions.

So maybe only trigger them on push on main, and only for light jobs?

**Comment by inmzhang** [comment]
> So maybe only trigger them on push on main, and only for light jobs?

Totally agree.
