### ISSUE TITLE
Add benchmarks to the repository

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#328]
**Is your feature request related to a problem? Please describe.**

We are currently in a consolidation phase during which we do not aim at implementing new features but rather refactor the current code to make it better. One (but absolutely not the only) way of evaluating if a new code is "better" than the previous one is to look at the time it takes to accomplish its goal, for us the time the `tqec` library takes to generate a valid `stim.Circuit` instance with observables and detectors.

That means that, during this consolidation phase, we may try to optimize the `tqec` code for runtime. [Initial benchmarks](https://github.com/QCHackers/tqec/pull/321#issuecomment-2374198718) seem to show that there are currently two main bottlenecks (again, only speaking about runtime here):

- automatic detector computation,
- transformation from `cirq.Circuit` to `stim.Circuit`,

but these benchmarks should be replicated and, if possible, improved to be sure that the above points are indeed bottlenecks.

**Describe the solution you'd like**

A collection of **meaningful** benchmarks to illustrate the current runtime performance of the `tqec` library and guide the development towards a more efficient circuit generation with high confidence that our efforts will be rewarded by a non-insignificant gain in runtime performance.

**Additional context**

Runtime performance is important, but is absolutely not the only way of quantifying whether or not a code is "better" than another one. Among the other important factors I can list:

- documentation,
- testing,
- simplicity of the code,

and I am pretty sure I am forgetting a few. All that to say that runtime performance is not the ultimate goal (yet) and other factors should also be taken into account when making large code base changes.

**Comment by inmzhang** [comment]
Setting up performance benchmarks and criteria would be great when doing a large refactor of the codebase!

By the way, I’m on a one-week holiday and won’t be able to do coding. However, I can still do some simple code reviews and approve changes to help avoid blocking.
