### ISSUE TITLE
What is the best (most idiomatic?) way to implement plaquettes?

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#337]
**Is your feature request related to a problem? Please describe.**

From a [comment thread](https://github.com/QCHackers/tqec/pull/334#discussion_r1789772177):

@inmzhang 
> For CNOT based circuits, I suggest to use X-basis reset/measurement instead of Z-basis ones with H gates. So this can be "RX - CX - CX - MX". The same for other X-basis plaquettes. This is followed by the convention that is widely used in the QEC papers:
> 1. CZ-based gateset(CZ, RZ, MZ, ...) which is used by the superconducting architecture and can be tested under SI1000 noise model.
> 2. CX-based gateset(CX, RZ, MZ, RX, MX) which is a universal test case for the code performance and usually is tested under uniform depolarizing noise model.

@nelimee 
> That would simplify things a little bit. What about Pauli syndromes measuring ZXXZ? I do not see a way of "removing" the H here.

@inmzhang 
> I suppose you mean `ZXXZ` plaquettes used in Google's experiment. They use the CZ-based gateset and then there should be a moment of H gates after resets and before measurements. But for the standard CSS type surface code here, with `RX`/`MX` available, the moment of H gates can be removed safely.
> Maybe Austin @afowler can provide some opinions on the usage of the different gatesets?

What is the best (most idiomatic?) way to implement plaquettes?

**Comment by afowler** [comment]
Start with RX-CNOT-MX and RZ-CNOT-MZ circuits for testing and debugging and
benchmarking with depolarizing noise then exchange each CNOT with H-CZ-H
and expand RX and MX using H. You'll find that every weight 4 plaquette
becomes the same up to interaction order, and you'll have 10 moments,
R-H-CZ-H-CZ-CZ-H-CZ-H-M. The H gates amongst the CZ gates will be on the
data qubits.

Best,
Austin.

**Comment by afowler** [comment]
Figure S12 of https://arxiv.org/abs/2408.13687 contains the full circuit
for the surface code on Google hardware.

Best,
Austin.
