### ISSUE TITLE
Adapt to new RGB color convention for sketchup model

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#349]
In the last meeting, a new RGB color convention was introduced to incorporate the Y-basis measurement:
![图片](https://github.com/user-attachments/assets/ab939eb4-08e8-4526-820a-23d96f37a740)

It would be beneficial to adapt to the new convention as soon as possible to avoid distraction. However, the `RGB` value provided in the above picture needs to be checked. In particular, the `RGB` value for the blue face seems incorrect.

Austin @afowler, could you check and decide the color convention here? Also, could you provide the new `template.skp` and `template.dae` files?

**Comment by afowler** [comment]
You are right, I had a couple of digits reversed in blue:

B: 115, 150, 255

I've also updated the slide. I will send you the new color template in a
separate email.

**Comment by inmzhang** [comment]
<img width="289" alt="截屏2024-10-11 10 09 50" src="https://github.com/user-attachments/assets/a326058f-6972-42d7-bd1a-a66bbb0aa310">

The `Y` cube in the components is not colored. Currently, I do not have access to an old version of SketchUp, could you help with fixing that?

**Comment by afowler** [comment]
Ok, sending another try direct to you.
