### ISSUE TITLE
Circuit of `XZZX` plaquette

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#355]
Currently, the plaquettes for `ZXXZ` surface code all measure `ZXXZ` stabilizer follow the "Z" shape or "N" shape CZ order for different plaquette basis:

![图片](https://github.com/user-attachments/assets/6816e48d-b81b-4894-95e1-66cbea79faf8)

However, when I think about the Hadamard transition in the time direction for ZXXZ code, I realize that the measured stabilizer should be transformed from `ZXXZ` to `XZZX` when the boundary types exchange. So it means we need to use `ZXXZ` stabilizers for `XZ?` cubes while using `XZZX` stabilizers for `ZX?` cubes, which is not the case in the current code. The circuit I constructed for `XZZX` stabilizer measurement is as follow, some hadamard gates are inserted deliberately to balance the detection region for errors of different basis:

![图片](https://github.com/user-attachments/assets/dcf69794-43b3-4ca5-b561-eb1d2df3af2c)

And [here](https://algassert.com/crumble#circuit=Q(0,1)0;Q(0.5,0.5)1;Q(0.5,1.5)2;Q(1,0)3;Q(1,1)4;Q(1,2)5;Q(1.5,0.5)6;Q(1.5,1.5)7;Q(2,1)8;R_4;POLYGON(0,0,1,0.25)3_6_1;POLYGON(0,0,1,0.25)2_7_5;POLYGON(1,0,0,0.25)1_2_0;POLYGON(1,0,0,0.25)6_8_7;TICK;H_4;TICK;CZ_4_3;TICK;H_3_8_5_0;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_3_8_5_0;TICK;CZ_4_5;TICK;H_4;TICK;M_4;TICK;R_4;MARKZ(0)4;TICK;H_4;TICK;CZ_4_3;TICK;H_3_8_5_0;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_3_8_5_0;TICK;CZ_4_5;TICK;H_4;TICK;M_4;MARKZ(0)4;TICK;TICK;H_3_8_5_0;POLYGON(0,0,1,0.25)1_2_0;POLYGON(0,0,1,0.25)6_8_7;POLYGON(1,0,0,0.25)3_6_1;POLYGON(1,0,0,0.25)2_7_5;TICK;TICK;R_4;MARKZ(0)4;TICK;TICK;H_4_3_5_0_8;TICK;CZ_4_3;TICK;H_0_8_3_5;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_0_8_3_5;TICK;CZ_4_5;TICK;H_4_3_5_0_8;TICK;M_4;MARKZ(0)4;TICK;R_4;TICK;H_4_3_5_0_8;TICK;CZ_4_3;TICK;H_0_8_3_5;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_0_8_3_5;TICK;CZ_4_5;TICK;H_4_3_5_0_8;TICK;M_4) is the Crumble link of the transition round from `ZXXZ` to `XZZX`.

I cannot be sure whether this is the ideal circuit for `XZZX` stabilizer measurement and whether we do really need `XZZX` stabilizers. Austin @afowler, could you check this out?

**Comment by afowler** [comment]
Hi Yiming,

Whatever circuit you used to measure the stabilizers before the layer of
H gates, after this layer you need to take the entire circuit and rotate it
90°. This does indeed mean that if you are using ZXXZ stabilizers, after
transversal H you will be using XZZX stabilizers. Note that in crumble you
can get the required circuit by selecting the entire circuit and rotating
it twice 45°.

Please let me know if this answers your questions.

Regards,
Austin.

**Comment by inmzhang** [comment]
> Whatever circuit you used to measure the stabilizers before the layer of
H gates, after this layer you need to take the entire circuit and rotate it
90°

Yes I understand rotate the circuit by 90 degree will correctly implement the stabilizers. But the rotation will also change the CZ ordering to that we don't want, for example:
```txt
1     2                                 2      4
                ----rotate---->      
3     4                                 1      3
````
To make spatial hadamard and spatial junctions to work properly, we need to adjust the interaction ordering back to
```txt
1     3 

2     4 
```

For CSS surface code, it's trivial to adjust CNOT/CZ ordering because all the stabilizer consists of the same Pauli operator. But for ZXXZ surface code, that means transformation from `CZ -> CNOT -> CNOT -> CZ` to `CNOT -> CZ -> CZ -> CNOT` so we need to recompile the circuits to `CZ + H`, which results in the circuit below:

![图片](https://github.com/user-attachments/assets/dcf69794-43b3-4ca5-b561-eb1d2df3af2c)

Is my understanding correct?

**Comment by afowler** [comment]
Thanks for the discussion, I'll look into it in detail later tonight.

**Comment by afowler** [comment]
Let's go step-by-step.

First, a completely standard CNOT-based distance 3 surface code with a
round of stabilizer measurement before and after transversal Hadamard. Link
<https://algassert.com/crumble#circuit=Q(0,1)0;Q(0.5,0.5)1;Q(0.5,1.5)2;Q(0.5,2.5)3;Q(1,1)4;Q(1,2)5;Q(1,3)6;Q(1.5,0.5)7;Q(1.5,1.5)8;Q(1.5,2.5)9;Q(2,0)10;Q(2,1)11;Q(2,2)12;Q(2.5,0.5)13;Q(2.5,1.5)14;Q(2.5,2.5)15;Q(3,2)16;POLYGON(0,0,1,0.25)7_13_14_8;POLYGON(0,0,1,0.25)2_8_9_3;POLYGON(0,0,1,0.25)14_15;POLYGON(0,0,1,0.25)1_2;POLYGON(1,0,0,0.25)1_7_8_2;POLYGON(1,0,0,0.25)8_14_15_9;POLYGON(1,0,0,0.25)13_7;POLYGON(1,0,0,0.25)9_3;TICK;R_0_5_11_16;RX_4_10_12_6;MARKX(0)4;TICK;CX_4_1_12_8_6_3_7_11_14_16_2_5;TICK;CX_4_7_12_14_6_9_8_11_3_5_15_16;TICK;CX_4_2_12_9_10_7_13_11_1_0_8_5;TICK;CX_10_13_4_8_12_15_14_11_9_5_2_0;TICK;M_0_5_11_16;MX_10_4_12_6;MARKX(0)4;TICK;H_1_2_3_7_8_9_13_14_15;TICK;POLYGON(0,0,1,0.25)1_7_8_2;POLYGON(0,0,1,0.25)8_14_15_9;POLYGON(0,0,1,0.25)9_3;POLYGON(0,0,1,0.25)13_7;POLYGON(1,0,0,0.25)1_2;POLYGON(1,0,0,0.25)7_13_14_8;POLYGON(1,0,0,0.25)2_8_9_3;POLYGON(1,0,0,0.25)14_15;TICK;R_10_4_12_6;RX_0_5_11_16;MARKZ(0)4;TICK;CX_5_2_16_14_11_7_1_4_8_12_3_6;TICK;CX_5_3_11_8_16_15_7_4_14_12_9_6;TICK;CX_5_8_11_13_0_1_2_4_9_12_7_10;TICK;CX_5_9_11_14_0_2_8_4_15_12_13_10;TICK;M_10_4_12_6;MX_0_5_16_11;MARKZ(0)4>.
I've used Z and И shaped circuits both before and after as appropriate.

Next, pure substitution of every CNOT with H-CZ-H, no compilation. Link
<https://algassert.com/crumble#circuit=Q(0,1)0;Q(0.5,0.5)1;Q(0.5,1.5)2;Q(0.5,2.5)3;Q(1,1)4;Q(1,2)5;Q(1,3)6;Q(1.5,0.5)7;Q(1.5,1.5)8;Q(1.5,2.5)9;Q(2,0)10;Q(2,1)11;Q(2,2)12;Q(2.5,0.5)13;Q(2.5,1.5)14;Q(2.5,2.5)15;Q(3,2)16;POLYGON(0,0,1,0.25)7_13_14_8;POLYGON(0,0,1,0.25)2_8_9_3;POLYGON(0,0,1,0.25)14_15;POLYGON(0,0,1,0.25)1_2;POLYGON(1,0,0,0.25)1_7_8_2;POLYGON(1,0,0,0.25)8_14_15_9;POLYGON(1,0,0,0.25)13_7;POLYGON(1,0,0,0.25)9_3;TICK;R_0_5_11_16;RX_4_10_12_6;MARKX(0)4;TICK;H_1_11_8_5_16_3;TICK;CZ_4_1_7_11_12_8_2_5_14_16_6_3;TICK;H_1_11_8_5_16_3;TICK;H_7_11_14_5_16_9;TICK;CZ_4_7_12_14_8_11_15_16_6_9_3_5;TICK;H_7_11_14_5_16_9;TICK;H_7_0_11_2_5_9;TICK;CZ_1_0_4_2_12_9_8_5_13_11_10_7;TICK;H_7_0_11_2_5_9;TICK;H_13_0_11_8_5_15;TICK;CZ_10_13_14_11_2_0_4_8_9_5_12_15;TICK;H_13_0_11_8_5_15;TICK;M_0_5_11_16;MX_10_4_12_6;MARKX(0)4;TICK;H_1_2_3_7_8_9_13_14_15;TICK;POLYGON(0,0,1,0.25)1_7_8_2;POLYGON(0,0,1,0.25)8_14_15_9;POLYGON(0,0,1,0.25)9_3;POLYGON(0,0,1,0.25)13_7;POLYGON(1,0,0,0.25)1_2;POLYGON(1,0,0,0.25)7_13_14_8;POLYGON(1,0,0,0.25)2_8_9_3;POLYGON(1,0,0,0.25)14_15;TICK;R_10_4_12_6;RX_0_5_11_16;MARKZ(0)4;TICK;H_7_4_2_14_12_6;TICK;CZ_1_4_11_7_5_2_8_12_16_14_3_6;TICK;H_7_4_2_14_12_6;TICK;H_4_8_12_3_6_15;TICK;CZ_7_4_14_12_11_8_16_15_9_6_5_3;TICK;H_4_8_12_3_15_6;TICK;H_10_1_13_4_8_12;TICK;CZ_0_1_2_4_5_8_7_10_11_13_9_12;TICK;H_10_1_13_4_8_12;TICK;H_10_4_2_14_12_9;TICK;CZ_13_10_11_14_8_4_0_2_5_9_15_12;TICK;H_10_4_2_14_12_9;TICK;M_10_4_12_6;MX_0_5_16_11;MARKZ(0)4>
.

Next, expansion of R_X and M_X followed by cancellation of Hs wherever
possible. Link
<https://algassert.com/crumble#circuit=Q(0,1)0;Q(0.5,0.5)1;Q(0.5,1.5)2;Q(0.5,2.5)3;Q(1,1)4;Q(1,2)5;Q(1,3)6;Q(1.5,0.5)7;Q(1.5,1.5)8;Q(1.5,2.5)9;Q(2,0)10;Q(2,1)11;Q(2,2)12;Q(2.5,0.5)13;Q(2.5,1.5)14;Q(2.5,2.5)15;Q(3,2)16;POLYGON(0,0,1,0.25)7_13_14_8;POLYGON(0,0,1,0.25)2_8_9_3;POLYGON(0,0,1,0.25)14_15;POLYGON(0,0,1,0.25)1_2;POLYGON(1,0,0,0.25)1_7_8_2;POLYGON(1,0,0,0.25)8_14_15_9;POLYGON(1,0,0,0.25)13_7;POLYGON(1,0,0,0.25)9_3;TICK;R_0_5_11_16_10_4_12_6;MARKZ(0)4;TICK;H_1_11_8_5_16_3_10_4_12_6;TICK;CZ_4_1_7_11_12_8_2_5_14_16_6_3;TICK;H_1_8_3_7_14_9;TICK;CZ_4_7_12_14_8_11_15_16_6_9_3_5;TICK;H_14_16_0_2;TICK;CZ_1_0_4_2_12_9_8_5_13_11_10_7;TICK;H_7_2_9_13_8_15;TICK;CZ_10_13_14_11_2_0_4_8_9_5_12_15;TICK;H_0_11_5_10_4_12_6_1_3_9;TICK;M_0_5_11_16_10_4_12_6;MARKZ(0)4;TICK;POLYGON(0,0,1,0.25)1_7_8_2;POLYGON(0,0,1,0.25)8_14_15_9;POLYGON(0,0,1,0.25)9_3;POLYGON(0,0,1,0.25)13_7;POLYGON(1,0,0,0.25)1_2;POLYGON(1,0,0,0.25)7_13_14_8;POLYGON(1,0,0,0.25)2_8_9_3;POLYGON(1,0,0,0.25)14_15;TICK;R_10_4_12_6_0_11_5_16;MARKZ(0)4;TICK;H_4_12_6_0_11_5_16;TICK;CZ_1_4_11_7_5_2_8_12_16_14_3_6;TICK;H_7_2_14_8_3_15;TICK;CZ_7_4_14_12_11_8_16_15_9_6_5_3;TICK;H_3_15_6_10_1_13;TICK;CZ_0_1_2_4_5_8_7_10_11_13_9_12;TICK;H_1_13_8_2_14_9;TICK;CZ_13_10_11_14_8_4_0_2_5_9_15_12;TICK;H_10_4_2_14_12_9_0_5_11_16;TICK;M_10_4_12_6_0_5_11_16;MARKZ(0)4>
.

When there are more normal rounds of stabilizer measurement before and
after these rounds, additional H cancellations will be possible by merging
gates at the end and beginning of rounds.

Regards,
Austin.

**Comment by inmzhang** [comment]
Great, after some merging of Hs or insertion of pair of Hs, I think the circuit I constructed above should be equivalent to yours. I inserted some H pairs on the idle qubits, which fills the holes in some moments. I think it will be beneficial because:
1. It will be easier to write code for this.
2. In my experience, do parallel single qubit gates on all the qubits is better than some partial patterns on hardware at most time. This is also the case for the ZXXZ circuits in Google's paper.

**Comment by afowler** [comment]
+1 for the extra symmetry you describe below.

**Comment by inmzhang** [comment]
> Currently, the plaquettes for `ZXXZ` surface code all measure `ZXXZ` stabilizer follow the "Z" shape or "N" shape CZ order for different plaquette basis:
> 
> ![图片](https://private-user-images.githubusercontent.com/61700160/375755078-6816e48d-b81b-4894-95e1-66cbea79faf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTg2ODYsIm5iZiI6MTcyODcxODM4NiwicGF0aCI6Ii82MTcwMDE2MC8zNzU3NTUwNzgtNjgxNmU0OGQtYjgxYi00ODk0LTk1ZTEtNjZjYmVhNzlmYWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3MzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTQyZmQ1Mjk2ZGIzYzMxZWFhNmY1ZTk2NjllMmVhZWMxMzhiNjBlM2Y1NDU0YjE2ZTYwOGQ2YTVhNTJjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XpBzA-zF-w93y7Q3ddjjsZyeTgAtc_67BGVHTF_won0)
> 
> However, when I think about the Hadamard transition in the time direction for ZXXZ code, I realize that the measured stabilizer should be transformed from `ZXXZ` to `XZZX` when the boundary types exchange. So it means we need to use `ZXXZ` stabilizers for `XZ?` cubes while using `XZZX` stabilizers for `ZX?` cubes, which is not the case in the current code. The circuit I constructed for `XZZX` stabilizer measurement is as follow, some hadamard gates are inserted deliberately to balance the detection region for errors of different basis:
> 
> ![图片](https://private-user-images.githubusercontent.com/61700160/375780770-dcf69794-43b3-4ca5-b561-eb1d2df3af2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTg2ODYsIm5iZiI6MTcyODcxODM4NiwicGF0aCI6Ii82MTcwMDE2MC8zNzU3ODA3NzAtZGNmNjk3OTQtNDNiMy00Y2E1LWI1NjEtZWIxZDJkZjNhZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3MzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODRlYWUwNzlmMWVlMjljNWMyZjM5NDY5NTgzOGQ0NjQyYzEyMzdkNjc5MDY4ZGU2OGJlZTQ2NDM3ZDQxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.luBzO_4FcgyDTv-UR2lN9iKg9z_eI2nCZ4xlOqmJIJ0)
> 
> And [here](https://algassert.com/crumble#circuit=Q(0,1)0;Q(0.5,0.5)1;Q(0.5,1.5)2;Q(1,0)3;Q(1,1)4;Q(1,2)5;Q(1.5,0.5)6;Q(1.5,1.5)7;Q(2,1)8;R_4;POLYGON(0,0,1,0.25)3_6_1;POLYGON(0,0,1,0.25)2_7_5;POLYGON(1,0,0,0.25)1_2_0;POLYGON(1,0,0,0.25)6_8_7;TICK;H_4;TICK;CZ_4_3;TICK;H_3_8_5_0;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_3_8_5_0;TICK;CZ_4_5;TICK;H_4;TICK;M_4;TICK;R_4;MARKZ(0)4;TICK;H_4;TICK;CZ_4_3;TICK;H_3_8_5_0;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_3_8_5_0;TICK;CZ_4_5;TICK;H_4;TICK;M_4;MARKZ(0)4;TICK;TICK;H_3_8_5_0;POLYGON(0,0,1,0.25)1_2_0;POLYGON(0,0,1,0.25)6_8_7;POLYGON(1,0,0,0.25)3_6_1;POLYGON(1,0,0,0.25)2_7_5;TICK;TICK;R_4;MARKZ(0)4;TICK;TICK;H_4_3_5_0_8;TICK;CZ_4_3;TICK;H_0_8_3_5;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_0_8_3_5;TICK;CZ_4_5;TICK;H_4_3_5_0_8;TICK;M_4;MARKZ(0)4;TICK;R_4;TICK;H_4_3_5_0_8;TICK;CZ_4_3;TICK;H_0_8_3_5;TICK;CZ_4_8;TICK;CZ_4_0;TICK;H_0_8_3_5;TICK;CZ_4_5;TICK;H_4_3_5_0_8;TICK;M_4) is the Crumble link of the transition round from `ZXXZ` to `XZZX`.
> 

And I realized it's just "transversal H on data qubits" -> "ZXXZ" measurement circuit -> "transversal H on data qubits". So the manual merge/insertion approach finally reached the same result in "ZXXZ" circuit in the paper. And that's quite reasonable.
