### ISSUE TITLE
Define a clear standard for coordinate order in `stim` exports

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#359]
**Is your feature request related to a problem? Please describe.**
The current code make extensive use of several data-classes with explicit `x` and `y` attributes to avoid having to ask ourselves the question "should `x` coordinate be in the first position of this tuple or the second?". 

The only place where we still have that question is when we manipulate `stim` data-structures, that explicitly have no standard on coordinate order (see for examples the [`DETECTOR` instruction documentation](https://github.com/quantumlib/Stim/blob/main/doc/gates.md#DETECTOR): `There is no required convention for which coordinate is which.`)

We should have a `tqec` standard on coordinate order for `stim` instructions, that we enforce on all `tqec`-generated `stim` data-structures.

**Describe the solution you'd like**
Maybe a `StimInstructionCoordinates` data-structure with explicit `x` and `y` (and `z`, or `t`, ...?) attributes and a `to_stim_coords` method fixing the ordering. That would allow us to easily change the ordering if we find that our initial choice was bad.

**Comment by afowler** [comment]
x, y, t coordinates would make the most sense for detectors in Stim.
