### ISSUE TITLE
Refactor `computation` directory

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#375]
In my mind, the code related to `ZXGraph` and `BlockGraph` needs to be cleaned up and more tests need to be implemented. I will start working on that and try to solve #368 and #370 along the process.

**Comment by inmzhang** [comment]
Question: is the “immediate Y basis initialization following a Y basis measurement” a desired operation?

It’s important to me at this point because it will have effects on the details of some algorithms like observable search and may pose some additional complexity. Currently I assume it’s possible. Then it will occupy a single integer position in spacetime and a Y node in the graph can connect to both the past and future. If this is true, then do we need to add an additional “YY” cube in the template to enforce the integer constraint? Austin @afowler, what’s your opinion on that?

**Comment by inmzhang** [comment]
> In my mind at this point in time if you wish to include initialization as well as measurement, then initialization can be
in the second half of a cube.

I think this is exactly what I mean by "immediate Y basis initialization following a Y basis measurement". Just to be sure, do you mean that we can forbid the cube in the following figure?

![图片](https://github.com/user-attachments/assets/4abff1d3-d8dc-48e6-a820-1d9576585a32)

**Comment by afowler** [comment]
Correct, forbidden for the moment. Little if anything is lost by forbidding
this. Measurement in the first half of a cube, initialization in the second
half, but both in different cubes for the moment.
