### ISSUE TITLE
Use a sphinx theme that supports dark mode natively

### ISSUE THREAD

**Issue by inmzhang** [QCHackers/tqec#382]
Currently we are using "Read The Docs" theme for our Sphinx-generated documentation pages. However, there are many additional theme options available to explore at https://sphinx-themes.readthedocs.io/en/latest/.

Personally, I prefer the [PyData](https://sphinx-themes.readthedocs.io/en/latest/sample-sites/pydata-sphinx-theme/) or [Furo](https://sphinx-themes.readthedocs.io/en/latest/sample-sites/furo/). Both support dark mode natively and, in my view, offer a cleaner, more modern style. For example, `Qualtran` uses the PyData theme for [their docs](https://qualtran.readthedocs.io/en/latest/index.html), which has a really nice look.

Do you have any preferences or thoughts on this?

**Comment by afowler** [comment]
No issue from my end if you have a strong preference and would prefer to
change the style.
