### ISSUE TITLE
Implement a horizontal Z movement QEC 

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#50]
Implement the following TQEC:

![experiment1](https://github.com/QCHackers/tqec/assets/12374487/a57031f8-82e1-4521-ab7c-5ea7474d2e39)

Needs at least #45 fixed.

Idea provided by Austin.

**Comment by nelimee** [comment]
Note that I received a mail yesterday evening (just after my message on the Google group) from someone (I do not know if he/she want his/her name publicly here) that will also likely be interested in that. 
Go ahead, you might be joined by at least someone else.

**Comment by inmzhang** [comment]
That's totally fine. It's no problem anyone else would like to work on this. Regardless of whether my own PR is finally accepted, it should still be an experience of learning in qec :)
