### ISSUE TITLE
Cannot run Jupyter Lab after server reset

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#56]
After restarting the JupyterLab, this error can occur:
```sh
$ python -m jupyter lab
Traceback (most recent call last):
  File "/home/codespace/.local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyterlab/__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 23, in <module>
    from jupyter_events import EventLogger
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyter_events/logger.py", line 19, in <module>
    from .schema import SchemaType
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyter_events/schema.py", line 9, in <module>
    from referencing import Registry
  File "/home/codespace/.local/lib/python3.10/site-packages/referencing/__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "/home/codespace/.local/lib/python3.10/site-packages/referencing/_core.py", line 89, in <module>
    class Specification(Generic[D]):
  File "/home/codespace/.local/lib/python3.10/site-packages/referencing/_core.py", line 115, in Specification
    ] = field(alias="anchors_in")
TypeError: field() got an unexpected keyword argument 'alias'
```

**Comment by afowler** [comment]
I'd also add that I can run the notebooks once after install, but after I
shut down the notebook get this error when I try to restart the notebook.

**Comment by nelimee** [comment]
May be linked with #35

**Comment by nelimee** [comment]
This error is likely due to an issue with versions. 

Prior to #59 being fixed, the `tqec` package installation raised a few warnings about unmatched version requirements. This is no longer the case.

I cannot replicate this issue on my computer. It would be nice if people that experienced this could try to re-install from scratch and replicate this issue. If it is not replicable, then we can likely close it.

Also, if your python version is 3.11 or above, you will see warnings in the jupyter console:
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```
This is normal and expected as explained in [https://stackoverflow.com/a/75274358/4810787](https://stackoverflow.com/a/75274358/4810787):

> This is just a warning that the debugger cannot debug frozen modules.
> > In Python 3.11, the core modules essential for Python startup are “frozen”. ... This reduces the steps in module execution process ... Interpreter startup is now 10-15% faster in Python 3.11. This has a big impact for short-running programs using Python.
>
> — What’s New In Python 3.11 § [Faster Startup](https://docs.python.org/3/whatsnew/3.11.html#faster-startup)
> > it's not possible for the debugger to debug frozen modules as the filename is definitely required to hit breakpoints
>
> — https://github.com/fabioz/PyDev.Debugger/issues/213#issuecomment-1058247166
> E.g. os.path.realpath.__code__.co_filename is now '<frozen posixpath>' in Python 3.11.

so these warnings should not be considered an issue.

**Comment by smburdick** [comment]
Since I consistently have this problem somehow, I usually don't run Jupyter Labs locally, I just use Collab.

**Comment by nelimee** [comment]
I think we can consider this issue fixed. If anyone still have problems regarding what has been brought up in this issue, please react here. In the absence of reaction in the next few days, I will close the issue.

**Comment by afowler** [comment]
This used to be an issue for me and is no longer. The installation guide
seems to be a little corrupted, however, and could use a revision to remove
unnecessary steps. There seem to be two installation commands, and I
believe only one should be necessary.

**Comment by nelimee** [comment]
> This used to be an issue for me and is no longer. The installation guide seems to be a little corrupted, however, and could use a revision to remove unnecessary steps. There seem to be two installation commands, and I believe only one should be necessary.

Nice, I'll close this issue then. I made #78 to fix the README, thanks for bringing that up.
