### ISSUE TITLE
Create GitHub actions for CRs and deployment

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#58]
I know we have webpack automatically setup for the frontend, but I'm also thinking about the backend as well as the endpoints we have for both of them. We should create some actions to deploy the code to these endpoints whenever a change has occured. We should also run some tests automatically when a PR is opened (just like cirq).

**Comment by nelimee** [comment]
If you need anything on the backend side please ping me. I expect #35 to be annoying for that issue.

**Comment by smburdick** [comment]
> If you need anything on the backend side please ping me. I expect #35 to be annoying for that issue.

I don't think that will be a big problem since there aren't that many requirements.

**Comment by nelimee** [comment]
This issue is not relevant anymore. Closing it. See #323 for more details.
