### ISSUE TITLE
Rename `tqecjs`

### ISSUE THREAD

**Issue by vtomole** [QCHackers/tqec#60]
@smburdick Thanks. Let's move the discussion renaming of `tqecjs` elsewhere.

_Originally posted by @vtomole in https://github.com/QCHackers/tqec/issues/41#issuecomment-1904868521_

**Comment by vtomole** [comment]
@rryoung98 Thoughts?

**Comment by rryoung98** [comment]
sounds great :)

**Comment by smburdick** [comment]
Done.
