### ISSUE TITLE
Frontend compilation error

### ISSUE THREAD

**Issue by giangiac** [QCHackers/tqec#85]
Following the install instructions:
`> npm install`
generate a few warnings that aren't stoppers (I think due to conflicting dependencies).

Then I launch the development mode:
`> npm start`
and gets:

![image](https://github.com/QCHackers/tqec/assets/30329377/e140f4cc-6a2c-4d63-91e4-fccfed32d9ce)

NOTE: I am running on a remote Linux server using VSCode from a Windows laptop.

**Comment by smburdick** [comment]
@giangiac To run the frontend, you'll need to run
```sh
 npm start DISABLE_ESLINT_PLUGIN=true
```
I'm working on a PR (#83) to fix the formatting everywhere so the disable argument is no longer needed.

Beyond that, there is still a bug in the main branch (#82) which also needs to be addressed
