### ISSUE TITLE
Allow user to specify qubit lattice

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#91]
The current UI only allows 2 unit vertically/horizontally separated qubits, which is conducive for Google architecture superconducting quantum computers, but not, for example, IBM's.

We need to support manual tiling, instead of enforcing a single tiling, as specified in the updated task flow.

- [x] When the app is opened, there is only a grid with no qubits.
- [x] Prompt the user to specify a constellation of qubits
- [x] Create a rectangular (minimal) bounding box around the qubits
- [x] Allow the user to resize the parallelogram by dragging individual vertices to other grid points, allowing them to select a new grid point if the updated parallelogram still contains the entire constellation
- [x] Once those prompts are completed, the grid tessellates, filling the entire grid with qubits per the tiling.

~~- [ ] [Optional] Offer additional "shape modes", such as (general) quadrilateral, triangle, and hexagon~~

Alternatively, we could prompt the user to specify two non-parallel vectors to create the parallelogram, but this approach is less intuitive, and mathematically equivalent to the above procedure.

**Comment by afowler** [comment]
In my mind you want to be able to specify a constellation of qubits, and 2
vectors that define the two-dimensional tiling of that constellation of
qubits. This should be general enough for our purposes. You could choose to
throw an error if the tiling leads to more than one qubit at a specific
coordinate or simply count duplicate positions as a single qubit.

**Comment by smburdick** [comment]
@afowler The only example lattice I know of is the one we have implemented. Are you able to point out any resources that describe alternative lattices?

One example I found is this one from IBM: https://research.ibm.com/blog/heavy-hex-lattice

I feel that the most intuitive way to go about this from a programming standpoint is to provide as a parameter a planar graph that specifies the minimal relationship between a set of qubits.

In the tqec example, the minimal topology would comprise a single qubit in the center, with an edge of length 2 expanding north, south, east and west, implying another node (qubit) at the end of the cardinal points, like so:

```
   |
   |
-- * --
   |
   |
```

where each dashed line represents a unit edge.

**Comment by smburdick** [comment]
>  I do not personally think
we need to specify the couplers between qubits, rather just the
constellation of qubits themselves and then let the user understand which
qubits are coupled in which are not.

I'm not sure I understand what you mean exactly by a "constellation of qubits." My previous comment was an attempt to encapsulate the minimal information needed to construct the grid of qubits, which I then interpreted as a graph that would be used as a parameter to the `QubitLattice` class constructor or method.

**Comment by smburdick** [comment]
[heavy hex.pdf](https://github.com/QCHackers/tqec/files/14118724/heavy.hex.pdf)

There's the attachment.

**Comment by nelimee** [comment]
From what I understood, the minimum information required would be:
1. One group of qubits (the qubits enclosed in green rectangles in @afowler document). 
2. Two 2-dimensional vectors of integers that describes how each unit group of qubits should be translated to have the lattice.

Mathematically, the group of qubits is a set 
$$S = \left\\{ q = \left( i, j \right) \, \text{ with } \left(i, j\right) \in \mathbb{N}^* \right\\},$$
and the tiling will be obtained by shifting all the qubits of $S$ by integers multiples of the two 2-dimensional vectors
$$V_1 = \left( v_1^1, v_1^2 \right)\qquad V_2 = \left( v_2^1, v_2^2 \right)$$ giving
$$S' = \left\\{ q = \left(\left( i, j \right) + x V_1 + y V_2\right) \, \text{ with } \left(i, j, x, y\right)\in\mathbb{N}^* \right\\}.$$

The unit group of qubits ($S$) can be obtained by simply clicking on the regular grid of qubits we have right now (or even a denser one), and the 2 vectors can probably be specified by dragging or in a specific mode?

**Comment by smburdick** [comment]
I just spoke with @afowler and we've updated Task 1 to incorporate the updates we need. I will update this issue and self-assign.

**Comment by smburdick** [comment]
@Gistbatch to your point, both tasks 1 and 2 require the users to specify qubits, but at different application stages, and I think it would make sense to keep these actions logically separate.

**Comment by smburdick** [comment]
My plan is to demo up to the third sub-task on Wednesday

**Comment by smburdick** [comment]
I can definitely demo subtasks 1-3 and 5 tomorrow.
